# Defining services for Docker Compose
version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_rootcode
    hostname: postgres_rootcode
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
  
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_container
    hostname: mailhog_container
    ports:
      - "${SMTP_PORT}:1025"  # SMTP server
      - "${WEB_PORT}:8025"   # Web UI
    environment:
      - MH_STORAGE=memory    # Use memory storage instead of maildir
    networks:
      - default

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local